### PR TITLE
Responsive Web Design- Milestone

### PR DESCRIPTION
**Pull request by shubhsk88**
## TNW Website Responsive design

This PR address the implementation of the clone of the next web page which is a part of microverse project. In this PR we implemented

- The responsive design of the webpage using Media Queries
- Used Grid Layout and flexbox for the design of the Overall Layout
-  Used font awesome to replace the icon provided in the website

### CODE REVIEW

**Review by serdg0 — CHANGES_REQUESTED** [review]
**Status: Require Changes.**

Hello @shubhsk88  and @emiliocm9 ! :v: :v: 

Great work! The project overall looks great but there are some things we must change before making in it **outstanding** :trophy: :trophy: 

This project is about playing and observing the responsive behavior of the TNW site and implement it.

Here are the required changes:

**General**

- [ ] HTML Semantics. Use article tags instead of div tags.

**Navbar**
Selection_011

- [x] Padding in links

- [x] Large - TNW logo doesn' appear until medium size (768px < Medium < 1024)

**Latest news section**

- [ ] Header name. Change 'Latest Articles' to 'Latest news'.

- [ ] Responsivness. At large ( > 1024px ) screens each row should only display 4 articles.

**Categories Section**

- [ ] At large screens, each row align 3 articles.

**Latest Deals Section**

- [ ] At large screen each row allignt 4 articles.
- [ ] At medium screen each row allign 3 articles.

**Footer**
Selection_012

- [ ] In small screen the logos are overflowing.


Make those changes and submit for another code review.

So far the project is looking great! Judging by the work you won't have any problems making those changes. :1st_place_medal: :1st_place_medal: 

Feel free to reach me in slack if anything.

### Happy Coding! :computer: :computer: 

Sergio Diaz Gonzalez.

**Comment by shubhsk88** [comment]
Thank you for your feedback!!! but about the TNW logo that logo also visible in the big screen and you can see when you scroll down the website You can see the same in the screenshot
Screenshot (169)

**Comment by lekegitrepo** [comment]
### Hi Team 👍 👏 
### You have done a good job ⭐ but you need to fix this 👇 before your project can be approved.

#### Required:
**_Fix the horizontal scroll bar on the page._**

**_if you have any doubts or questions contact me on slack._**

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Request changes.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi **TEAM**, you have done a great job implementing all the changes requested by the previous TSE's 👍 I hereby approve of your project, but before we merge let us fix the issue below:
- Let us compare our version to the original and hide the TNW logo
```Currently```
qf1
```Original```
qf2


Good luck with your next projects 😄 
Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Pull request merged**
